"""Initial multidb setup

Revision ID: 7ec8a171e084
Revises: 
Create Date: 2026-03-04 10:33:23.426953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ec8a171e084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_oltp() -> None:
    """Upgrade oltp schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_forecast', 'weather_date',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False)
    op.alter_column('weather_forecast', 'forecast_date',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=False)
    op.alter_column('weather_forecast', 'weather_place',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               nullable=False)
    op.alter_column('weather_forecast', 'temperature_2m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_2m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'dew_point_2m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'precipitation_probability',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'precipitation',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'rain',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'showers',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'snowfall',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_low',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_mid',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_high',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'evapotranspiration',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_10m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_80m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_120m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_180m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_10m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_80m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_120m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_180m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_gusts_10m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_80m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_120m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_180m',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'soil_moisture_1_to_3cm',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'soil_moisture_9_to_27cm',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_950hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_925hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_900hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_850hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_800hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_950hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_925hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_900hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_850hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_800hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_950hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_925hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_900hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_850hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_800hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_950hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_925hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_900hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_850hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_800hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_925hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_900hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_850hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_800hpa',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_oltp() -> None:
    """Downgrade oltp schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_forecast', 'wind_direction_800hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_850hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_900hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_925hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_800hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_850hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_900hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_925hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_950hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_800hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_850hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_900hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_925hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_950hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_800hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_850hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_900hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_925hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_950hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_800hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_850hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_900hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_925hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_950hpa',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'soil_moisture_9_to_27cm',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'soil_moisture_1_to_3cm',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_180m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_120m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_80m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_gusts_10m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_180m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_120m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_80m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_direction_10m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_180m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_120m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_80m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'wind_speed_10m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'evapotranspiration',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_high',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_mid',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover_low',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'cloud_cover',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'snowfall',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'showers',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'rain',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'precipitation',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'precipitation_probability',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'dew_point_2m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'relative_humidity_2m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'temperature_2m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_forecast', 'weather_place',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('weather_forecast', 'forecast_date',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True)
    op.alter_column('weather_forecast', 'weather_date',
               existing_type=postgresql.TIMESTAMP(precision=0),
               nullable=True)
    # ### end Alembic commands ###


def upgrade_dwh() -> None:
    """Upgrade dwh schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=150), nullable=False),
    sa.Column('city_postal_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('city_name')
    )
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('street',
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('street_id'),
    sa.UniqueConstraint('street_name')
    )
    op.create_table('weather_forecast',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('weather_date', postgresql.TIMESTAMP(precision=0), nullable=False),
    sa.Column('forecast_date', postgresql.TIMESTAMP(precision=0), nullable=False),
    sa.Column('weather_place', sa.String(length=150), nullable=False),
    sa.Column('temperature_2m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_2m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dew_point_2m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation_probability', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rain', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('showers', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('snowfall', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_msl', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('surface_pressure', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_low', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_mid', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_high', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('evapotranspiration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_80m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_120m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_180m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_80m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_120m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_180m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_gusts_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_80m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_120m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_180m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('soil_moisture_1_to_3cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('soil_moisture_9_to_27cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_950hpa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_direction_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address_street_number', sa.String(length=10), nullable=True),
    sa.Column('address_city_id', sa.Integer(), nullable=False),
    sa.Column('address_street_id', sa.Integer(), nullable=True),
    sa.Column('address_country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_city_id'], ['city.city_id'], ),
    sa.ForeignKeyConstraint(['address_country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['address_street_id'], ['street.street_id'], ),
    sa.PrimaryKeyConstraint('address_id'),
    sa.UniqueConstraint('address_street_number', 'address_city_id', 'address_street_id', 'address_country_id')
    )
    op.create_table('pilot',
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('pilot_number', sa.Integer(), nullable=False),
    sa.Column('pilot_firstname', sa.String(length=150), nullable=False),
    sa.Column('pilot_lastname', sa.String(length=150), nullable=False),
    sa.Column('pilot_email', sa.String(length=250), nullable=False),
    sa.Column('pilot_phone', sa.String(length=20), nullable=True),
    sa.Column('pilot_birthday', sa.Date(), nullable=True),
    sa.Column('pilot_address_id', sa.Integer(), nullable=True),
    sa.Column('pilot_maxdistance', sa.Integer(), nullable=True),
    sa.Column('pilot_license_number', sa.String(length=150), nullable=True),
    sa.Column('pilot_validator', sa.Boolean(), nullable=True),
    sa.Column('pilot_validator_score', sa.Integer(), nullable=True),
    sa.Column('pilot_password_hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['pilot_address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('pilot_id')
    )
    op.create_table('takeoff',
    sa.Column('takeoff_id', sa.Integer(), nullable=False),
    sa.Column('takeoff_name', sa.String(length=150), nullable=False),
    sa.Column('takeoff_latitude', sa.Float(), nullable=False),
    sa.Column('takeoff_longitude', sa.Float(), nullable=False),
    sa.Column('takeoff_type', sa.String(length=150), nullable=True),
    sa.Column('takeoff_directionDegreeMin', sa.Integer(), nullable=True),
    sa.Column('takeoff_directionDegreeMax', sa.Integer(), nullable=True),
    sa.Column('takeoff_globalDirection', sa.String(length=150), nullable=True),
    sa.Column('takeoff_elevation', sa.Integer(), nullable=True),
    sa.Column('takeoff_verticalDrop', sa.Integer(), nullable=True),
    sa.Column('takeoff_difficulty', sa.String(length=30), nullable=True),
    sa.Column('takeoff_comment', sa.Text(), nullable=True),
    sa.Column('takeoff_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['takeoff_address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('takeoff_id')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_starttime', postgresql.TIMESTAMP(precision=0), nullable=False),
    sa.Column('flight_airtime', sa.Time(), nullable=False),
    sa.Column('flight_distance', sa.Integer(), nullable=True),
    sa.Column('flight_maxheight', sa.Integer(), nullable=True),
    sa.Column('flight_pilot_id', sa.Integer(), nullable=False),
    sa.Column('flight_takeoff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_pilot_id'], ['pilot.pilot_id'], ),
    sa.ForeignKeyConstraint(['flight_takeoff_id'], ['takeoff.takeoff_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.drop_table('dim_time')
    op.drop_table('dim_weather')
    op.drop_table('fact_fly')
    op.drop_table('dim_takeoff')
    op.drop_table('dim_date')
    op.drop_table('dim_pilot')
    # ### end Alembic commands ###


def downgrade_dwh() -> None:
    """Downgrade dwh schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_pilot',
    sa.Column('dim_pilot_sk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dim_pilot_bk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dim_pilot_maxdistance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dim_pilot_sk', name=op.f('dim_pilot_pkey')),
    sa.UniqueConstraint('dim_pilot_bk', name=op.f('dim_pilot_dim_pilot_bk_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dim_date',
    sa.Column('date_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_name', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('quarter_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('season', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_holiday_fwb', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_holiday_vl', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date_key', name=op.f('dim_date_pkey'))
    )
    op.create_table('dim_takeoff',
    sa.Column('dim_takeoff_sk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dim_takeoff_bk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dim_takeoff_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dim_takeoff_sk', name=op.f('dim_takeoff_pkey')),
    sa.UniqueConstraint('dim_takeoff_bk', name=op.f('dim_takeoff_dim_takeoff_bk_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('fact_fly',
    sa.Column('fact_fly_sk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fact_fly_bk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fact_fly_distance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fact_fly_airtime', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('fact_fly_pilot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fact_fly_takeoff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fact_fly_weather', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fact_fly_start_date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fact_fly_start_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fact_fly_pilot'], ['dim_pilot.dim_pilot_sk'], name=op.f('fact_fly_fact_fly_pilot_fkey')),
    sa.ForeignKeyConstraint(['fact_fly_start_date'], ['dim_date.date_key'], name=op.f('fact_fly_fact_fly_start_date_fkey')),
    sa.ForeignKeyConstraint(['fact_fly_start_time'], ['dim_time.time_key'], name=op.f('fact_fly_fact_fly_start_time_fkey')),
    sa.ForeignKeyConstraint(['fact_fly_takeoff'], ['dim_takeoff.dim_takeoff_sk'], name=op.f('fact_fly_fact_fly_takeoff_fkey')),
    sa.ForeignKeyConstraint(['fact_fly_weather'], ['dim_weather.dim_weather_sk'], name=op.f('fact_fly_fact_fly_weather_fkey')),
    sa.PrimaryKeyConstraint('fact_fly_sk', name=op.f('fact_fly_pkey')),
    sa.UniqueConstraint('fact_fly_bk', name=op.f('fact_fly_fact_fly_bk_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dim_weather',
    sa.Column('dim_weather_sk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dim_weather_bk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperature_2m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_2m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('dew_point_2m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('precipitation_probability', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('precipitation', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('rain', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('showers', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('snowfall', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('pressure_msl', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('surface_pressure', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_low', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_mid', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_high', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('evapotranspiration', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_10m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_80m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_120m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_180m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_10m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_80m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_120m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_180m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_gusts_10m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_80m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_120m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_180m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('soil_moisture_1_to_3cm', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('soil_moisture_9_to_27cm', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_950hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_950hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_950hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_950hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_950hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_950hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dim_weather_sk', name=op.f('dim_weather_pkey')),
    sa.UniqueConstraint('dim_weather_bk', name=op.f('dim_weather_dim_weather_bk_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dim_time',
    sa.Column('time_key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hour_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minute_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_of_day', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('time_key', name=op.f('dim_time_pkey'))
    )
    op.drop_table('flight')
    op.drop_table('takeoff')
    op.drop_table('pilot')
    op.drop_table('address')
    op.drop_table('weather_forecast')
    op.drop_table('street')
    op.drop_table('country')
    op.drop_table('city')
    # ### end Alembic commands ###


def upgrade_weather() -> None:
    """Upgrade weather schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=150), nullable=False),
    sa.Column('city_postal_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('city_name')
    )
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('street',
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('street_id'),
    sa.UniqueConstraint('street_name')
    )
    op.create_table('weather_forecast',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('weather_date', postgresql.TIMESTAMP(precision=0), nullable=False),
    sa.Column('forecast_date', postgresql.TIMESTAMP(precision=0), nullable=False),
    sa.Column('weather_place', sa.String(length=150), nullable=False),
    sa.Column('temperature_2m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_2m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dew_point_2m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation_probability', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('precipitation', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rain', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('showers', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('snowfall', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_msl', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('surface_pressure', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_low', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_mid', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_high', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('evapotranspiration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_80m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_120m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_180m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_80m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_120m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_180m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_gusts_10m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_80m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_120m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_180m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('soil_moisture_1_to_3cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('soil_moisture_9_to_27cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('relative_humidity_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cloud_cover_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_speed_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_950hpa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_direction_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_950hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_925hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_900hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_850hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('geopotential_height_800hpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address_street_number', sa.String(length=10), nullable=True),
    sa.Column('address_city_id', sa.Integer(), nullable=False),
    sa.Column('address_street_id', sa.Integer(), nullable=True),
    sa.Column('address_country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_city_id'], ['city.city_id'], ),
    sa.ForeignKeyConstraint(['address_country_id'], ['country.country_id'], ),
    sa.ForeignKeyConstraint(['address_street_id'], ['street.street_id'], ),
    sa.PrimaryKeyConstraint('address_id'),
    sa.UniqueConstraint('address_street_number', 'address_city_id', 'address_street_id', 'address_country_id')
    )
    op.create_table('pilot',
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('pilot_number', sa.Integer(), nullable=False),
    sa.Column('pilot_firstname', sa.String(length=150), nullable=False),
    sa.Column('pilot_lastname', sa.String(length=150), nullable=False),
    sa.Column('pilot_email', sa.String(length=250), nullable=False),
    sa.Column('pilot_phone', sa.String(length=20), nullable=True),
    sa.Column('pilot_birthday', sa.Date(), nullable=True),
    sa.Column('pilot_address_id', sa.Integer(), nullable=True),
    sa.Column('pilot_maxdistance', sa.Integer(), nullable=True),
    sa.Column('pilot_license_number', sa.String(length=150), nullable=True),
    sa.Column('pilot_validator', sa.Boolean(), nullable=True),
    sa.Column('pilot_validator_score', sa.Integer(), nullable=True),
    sa.Column('pilot_password_hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['pilot_address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('pilot_id')
    )
    op.create_table('takeoff',
    sa.Column('takeoff_id', sa.Integer(), nullable=False),
    sa.Column('takeoff_name', sa.String(length=150), nullable=False),
    sa.Column('takeoff_latitude', sa.Float(), nullable=False),
    sa.Column('takeoff_longitude', sa.Float(), nullable=False),
    sa.Column('takeoff_type', sa.String(length=150), nullable=True),
    sa.Column('takeoff_directionDegreeMin', sa.Integer(), nullable=True),
    sa.Column('takeoff_directionDegreeMax', sa.Integer(), nullable=True),
    sa.Column('takeoff_globalDirection', sa.String(length=150), nullable=True),
    sa.Column('takeoff_elevation', sa.Integer(), nullable=True),
    sa.Column('takeoff_verticalDrop', sa.Integer(), nullable=True),
    sa.Column('takeoff_difficulty', sa.String(length=30), nullable=True),
    sa.Column('takeoff_comment', sa.Text(), nullable=True),
    sa.Column('takeoff_address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['takeoff_address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('takeoff_id')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('flight_starttime', postgresql.TIMESTAMP(precision=0), nullable=False),
    sa.Column('flight_airtime', sa.Time(), nullable=False),
    sa.Column('flight_distance', sa.Integer(), nullable=True),
    sa.Column('flight_maxheight', sa.Integer(), nullable=True),
    sa.Column('flight_pilot_id', sa.Integer(), nullable=False),
    sa.Column('flight_takeoff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_pilot_id'], ['pilot.pilot_id'], ),
    sa.ForeignKeyConstraint(['flight_takeoff_id'], ['takeoff.takeoff_id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.drop_table('weather_historic')
    # ### end Alembic commands ###


def downgrade_weather() -> None:
    """Downgrade weather schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_historic',
    sa.Column('weather_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weather_date', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('temperature_2m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_2m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('dew_point_2m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('precipitation_probability', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('precipitation', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('rain', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('showers', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('snowfall', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pressure_msl', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('surface_pressure', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_low', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_mid', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_high', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('evapotranspiration', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_10m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_80m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_120m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_180m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_10m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_80m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_120m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_180m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_gusts_10m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_80m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_120m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_180m', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('soil_moisture_1_to_3cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('soil_moisture_9_to_27cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_950hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_925hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_900hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_850hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('temperature_800hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_950hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_925hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_900hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_850hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('relative_humidity_800hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_950hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_925hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_900hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_850hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cloud_cover_800hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_950hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_925hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_900hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_850hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_speed_800hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_950hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_925hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_900hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_850hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('wind_direction_800hpa', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_950hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_925hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_900hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_850hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('geopotential_height_800hpa', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('weather_place', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('weather_id', name=op.f('weather_historic_pkey'))
    )
    op.drop_table('flight')
    op.drop_table('takeoff')
    op.drop_table('pilot')
    op.drop_table('address')
    op.drop_table('weather_forecast')
    op.drop_table('street')
    op.drop_table('country')
    op.drop_table('city')
    # ### end Alembic commands ###

