from shared.database_file.extensions import db
from sqlalchemy.dialects.postgresql import TIMESTAMP


class Historicweather(db.Model):
    __tablename__ = 'weather_historic'
    __bind_key__ = "weather"


    weather_id = db.Column(db.Integer, primary_key=True)
    weather_date = db.Column(TIMESTAMP(timezone=False, precision=0), nullable=False)
    temperature_2m = db.Column(db.Numeric(6, 2))
    relative_humidity_2m = db.Column(db.Numeric(6, 2))
    dew_point_2m = db.Column(db.Numeric(6, 2))
    precipitation_probability = db.Column(db.Numeric(6, 2))
    precipitation = db.Column(db.Numeric(6, 2))
    rain = db.Column(db.Numeric(6, 2))
    showers = db.Column(db.Numeric(6, 2))
    snowfall = db.Column(db.Numeric(6, 2))
    pressure_msl = db.Column(db.Numeric(6, 2))
    surface_pressure = db.Column(db.Numeric(6, 2))
    cloud_cover = db.Column(db.Numeric(6, 2))
    cloud_cover_low = db.Column(db.Numeric(6, 2))
    cloud_cover_mid = db.Column(db.Numeric(6, 2))
    cloud_cover_high = db.Column(db.Numeric(6, 2))
    evapotranspiration = db.Column(db.Numeric(6, 2))
    wind_speed_10m = db.Column(db.Numeric(6, 2))
    wind_speed_80m = db.Column(db.Numeric(6, 2))
    wind_speed_120m = db.Column(db.Numeric(6, 2))
    wind_speed_180m = db.Column(db.Numeric(6, 2))
    wind_direction_10m = db.Column(db.Numeric(6, 2))
    wind_direction_80m = db.Column(db.Numeric(6, 2))
    wind_direction_120m = db.Column(db.Numeric(6, 2))
    wind_direction_180m = db.Column(db.Numeric(6, 2))
    wind_gusts_10m = db.Column(db.Numeric(6, 2))
    temperature_80m = db.Column(db.Numeric(6, 2))
    temperature_120m = db.Column(db.Numeric(6, 2))
    temperature_180m = db.Column(db.Numeric(6, 2))
    soil_moisture_1_to_3cm = db.Column(db.Numeric(6, 2))
    soil_moisture_9_to_27cm = db.Column(db.Numeric(6, 2))
    temperature_950hpa = db.Column(db.Numeric(6, 2))
    temperature_925hpa = db.Column(db.Numeric(6, 2))
    temperature_900hpa = db.Column(db.Numeric(6, 2))
    temperature_850hpa = db.Column(db.Numeric(6, 2))
    temperature_800hpa = db.Column(db.Numeric(6, 2))
    relative_humidity_950hpa = db.Column(db.Numeric(6, 2))
    relative_humidity_925hpa = db.Column(db.Numeric(6, 2))
    relative_humidity_900hpa = db.Column(db.Numeric(6, 2))
    relative_humidity_850hpa = db.Column(db.Numeric(6, 2))
    relative_humidity_800hpa = db.Column(db.Numeric(6, 2))
    cloud_cover_950hpa = db.Column(db.Numeric(6, 2))
    cloud_cover_925hpa = db.Column(db.Numeric(6, 2))
    cloud_cover_900hpa = db.Column(db.Numeric(6, 2))
    cloud_cover_850hpa = db.Column(db.Numeric(6, 2))
    cloud_cover_800hpa = db.Column(db.Numeric(6, 2))
    wind_speed_950hpa = db.Column(db.Numeric(6, 2))
    wind_speed_925hpa = db.Column(db.Numeric(6, 2))
    wind_speed_900hpa = db.Column(db.Numeric(6, 2))
    wind_speed_850hpa = db.Column(db.Numeric(6, 2))
    wind_speed_800hpa = db.Column(db.Numeric(6, 2))
    wind_direction_950hpa = db.Column(db.Numeric(5, 2))
    wind_direction_925hpa = db.Column(db.Numeric(6, 2))
    wind_direction_900hpa = db.Column(db.Numeric(6, 2))
    wind_direction_850hpa = db.Column(db.Numeric(6, 2))
    wind_direction_800hpa = db.Column(db.Numeric(6, 2))
    geopotential_height_950hpa = db.Column(db.Numeric(6, 2))
    geopotential_height_925hpa = db.Column(db.Numeric(6, 2))
    geopotential_height_900hpa = db.Column(db.Numeric(6, 2))
    geopotential_height_850hpa = db.Column(db.Numeric(6, 2))
    geopotential_height_800hpa = db.Column(db.Numeric(6, 2))
    weather_place = db.Column(db.String(200), nullable=False)